#include<iostream>
int main()
{
    int i =1;
    do 
    {
        std::cout<<i<<std::endl;
        i++;
    }while(i<=10);
   // int cout;
 //   cout=10;
    //std::cout<<"cout = "<< cout<<std::endl;
  // std:: cout<<"Hello"<<std::endl;
    //FOR LOOP
    //TO PRINT MY NAME.
    //100 TIMES
    //std::cout<<"My name is Abed"<<std::endl;
    //for(int count=1;/*condition*/count<=100;++count++)
    //{
      //  std::cout<<"My name is Abed"<<std::endl;
    //}
   // int count= 1;
   // while(count<=100)
    //{
      //std::  cout<<"My name is Abed"<<std::endl;
      //count++;
    //}
    /*
    do{
        std::cout<<"My name is Abed"<<std::endl;
    }while(count<=100);
    count++;*/
   // int num[10];
    //std::cout<<"size of num = "<<sizeof(num[10])<<" bytes"<<std::endl;
    //char abed[5];
    //abed[5]={'a','s','d'};
   // std::cin>>ch;
   // std::cout<<ch;
    /*
    std::cout<<"size of short int = "<<sizeof(short int)<<" bytes"<<std::endl;
    std::cout<<"size of long double = "<<sizeof(long double)<<" bytes"<<std::endl;
    std::cout<<"size of character = "<<sizeof(char)<<" bytes"<<std::endl;
    */
    return 0;
}